### ISSUE TITLE
Having a hard time tracking down the source of this error / Building the Dockerized Solution

### ISSUE THREAD

**Issue by devspacenine** [GoTeamEpsilon/ctakes-rest-service#72]
So I'm working on getting everything running in docker and I need some help getting unstuck on this issue. I have very limited (and ancient) experience with Java and zero experience with Spring/Tomcat, so I apologize if the solution is glaringly obvious.

I'm using a Dockerfile that inherits from this [tomcat docker image](https://github.com/docker-library/tomcat/blob/master/9.0/jdk8/openjdk/Dockerfile), with OpenJDK v8.x and Tomcat v9.0.29.

My Dockerfile
```docker
FROM tomcat:jdk8-openjdk
LABEL maintainer="corey@simpleltc.com"

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "maven", "subversion", "git", "unzip", "wget", "curl", "gettext", "gosu"]

WORKDIR /app/
RUN ["mkdir", "-p", "ctakes-codebase-area"]

COPY entrypoint.sh /app/
RUN ["chmod", "+x", "/app/entrypoint.sh"]

WORKDIR /app/ctakes-codebase-area/
RUN ["svn", "export", "https://svn.apache.org/repos/asf/ctakes/trunk"]

WORKDIR /app/ctakes-codebase-area/trunk/ctakes-distribution/
RUN ["mvn", "install", "-Dmaven.test.skip=true"]

WORKDIR /app/ctakes-codebase-area/trunk/ctakes-assertion-zoner/
RUN ["mvn", "install", "-Dmaven.test.skip=true"]

EXPOSE 8080

COPY ctakes-web-rest /app/ctakes-web-rest/

ENTRYPOINT ["/app/entrypoint.sh"]

WORKDIR $CATALINA_HOME

CMD ["catalina.sh", "run"]
```
And it starts an entrypoint script so that I can inject ENV variables as config values for Spring and cTAKES.
```bash
#!/bin/sh

set -e

cd /app/ctakes-web-rest/src/main/resources/org/apache/ctakes/dictionary/lookup/fast
cat customDictionary.xml | envsubst > customDictionary.xml

cd /app/ctakes-web-rest
mvn install
mv target/ctakes-web-rest.war /usr/local/tomcat/webapps/

exec "$@"
```
And here is the log output when I try to start up tomcat.

```bash
root@a31f8820f222:/app/ctakes-web-rest# catalina.sh run
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
07-Dec-2019 20:46:27.038 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.49
07-Dec-2019 20:46:27.041 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Nov 17 2019 18:45:30 UTC
07-Dec-2019 20:46:27.041 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.49.0
07-Dec-2019 20:46:27.041 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
07-Dec-2019 20:46:27.042 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-70-generic
07-Dec-2019 20:46:27.043 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
07-Dec-2019 20:46:27.043 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
07-Dec-2019 20:46:27.044 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_232-b09
07-Dec-2019 20:46:27.044 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
07-Dec-2019 20:46:27.045 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
07-Dec-2019 20:46:27.046 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
07-Dec-2019 20:46:27.046 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
07-Dec-2019 20:46:27.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
07-Dec-2019 20:46:27.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
07-Dec-2019 20:46:27.049 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
07-Dec-2019 20:46:27.049 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
07-Dec-2019 20:46:27.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
07-Dec-2019 20:46:27.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
07-Dec-2019 20:46:27.055 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
07-Dec-2019 20:46:27.058 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
07-Dec-2019 20:46:27.058 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.23] using APR version [1.5.2].
07-Dec-2019 20:46:27.059 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
07-Dec-2019 20:46:27.070 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
07-Dec-2019 20:46:27.082 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0l  10 Sep 2019]
07-Dec-2019 20:46:27.362 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
07-Dec-2019 20:46:27.393 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
07-Dec-2019 20:46:27.451 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
07-Dec-2019 20:46:27.459 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
07-Dec-2019 20:46:27.464 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1162 ms
07-Dec-2019 20:46:27.579 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
07-Dec-2019 20:46:27.580 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.49
07-Dec-2019 20:46:27.635 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ctakes-web-rest.war]
07-Dec-2019 20:46:40.180 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [ProgressAppender] additivity to [false].
log4j: Level value for ProgressAppender is  [INFO].
log4j: ProgressAppender level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%m].
log4j: Adding appender named [noEolAppender] to category [ProgressAppender].
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [ProgressDone] additivity to [false].
log4j: Level value for ProgressDone is  [INFO].
log4j: ProgressDone level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%m%n].
log4j: Adding appender named [eolAppender] to category [ProgressDone].
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{dd MMM yyyy HH:mm:ss} %5p %c{1} - %m%n].
log4j: Adding appender named [consoleAppender] to category [root].
07 Dec 2019 20:46:40  INFO DispatcherServlet - FrameworkServlet 'ctakes-rest-service': initialization started
07 Dec 2019 20:46:40  INFO XmlWebApplicationContext - Refreshing WebApplicationContext for namespace 'ctakes-rest-service-servlet': startup date [Sat Dec 07 20:46:40 UTC 2019]; root of context hierarchy
07 Dec 2019 20:46:41  INFO XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/ctakes-rest-service-servlet.xml]
07 Dec 2019 20:46:42  INFO RequestMappingHandlerMapping - Mapped "{[/analyze],methods=[POST]}" onto public java.util.Map<java.lang.String, java.util.List<org.apache.ctakes.rest.service.CuiResponse>> org.apache.ctakes.rest.service.CtakesRestController.getAnalyzedJSON(java.lang.String,java.util.Optional<java.lang.String>) throws java.lang.Exception
07 Dec 2019 20:46:43  INFO RequestMappingHandlerAdapter - Looking for @ControllerAdvice: WebApplicationContext for namespace 'ctakes-rest-service-servlet': startup date [Sat Dec 07 20:46:40 UTC 2019]; root of context hierarchy
07 Dec 2019 20:46:43  INFO RequestMappingHandlerAdapter - Looking for @ControllerAdvice: WebApplicationContext for namespace 'ctakes-rest-service-servlet': startup date [Sat Dec 07 20:46:40 UTC 2019]; root of context hierarchy
07 Dec 2019 20:46:43  INFO CtakesRestController - Initializing analysis engines and jcas pools
07 Dec 2019 20:46:43  INFO PiperFileReader - Loading Piper File pipers/Default.piper ...
07 Dec 2019 20:46:43  WARN PipelineBuilder - Thread count (3) is greater than core count (1).  Using core count for processing.
07 Dec 2019 20:46:43  INFO PiperFileReader - Loading Piper File pipers/TsDefaultTokenizerPipeline ...
......
.07 Dec 2019 20:46:45  INFO PiperFileReader - Loading Piper File pipers/TsChunkerSubPipe ...
..
07 Dec 2019 20:46:46  INFO PiperFileReader - Loading Piper File pipers/TsDictionarySubPipe ...
07 Dec 2019 20:46:46  WARN PiperFileReader - Attempted to set Parameter by Command-line options.  Command-line options are not specified.
07 Dec 2019 20:46:46  WARN PropertyAeFactory - No parameters specified.
07 Dec 2019 20:46:46  WARN PiperFileReader - Attempted to set Parameter by Command-line options.  Command-line options are not specified.
07 Dec 2019 20:46:46  WARN PropertyAeFactory - No parameters specified.
07 Dec 2019 20:46:46  WARN PiperFileReader - Attempted to set Parameter by Command-line options.  Command-line options are not specified.
07 Dec 2019 20:46:46  WARN PropertyAeFactory - No parameters specified.
.
07 Dec 2019 20:46:46  INFO PiperFileReader - Loading Piper File pipers/TsAttributeCleartkSubPipe ...
......

07 Dec 2019 20:46:48  INFO Chunker - Chunker model file: org/apache/ctakes/chunker/models/chunker-model.zip
07 Dec 2019 20:46:50  INFO CleartkAnalysisEngine - Finished initializing
07 Dec 2019 20:46:51  INFO ContextDependentTokenizerAnnotator - Finite state machines loaded.
07 Dec 2019 20:46:51  INFO CleartkAnalysisEngine - Starting initializing for Assigning Attributes
07 Dec 2019 20:46:52  INFO AbstractJCasTermAnnotator - Using dictionary lookup window type: org.apache.ctakes.typesystem.type.textspan.Sentence
07 Dec 2019 20:46:52  INFO AbstractJCasTermAnnotator - Exclusion tagset loaded: CC CD DT EX IN LS MD PDT POS PP PP$ PRP PRP$ RP TO VB VBD VBG VBN VBP VBZ WDT WP WPS WRB 
07 Dec 2019 20:46:52  INFO AbstractJCasTermAnnotator - Using minimum term text span: 3
07 Dec 2019 20:46:52  INFO AbstractJCasTermAnnotator - Using Dictionary Descriptor: org/apache/ctakes/dictionary/lookup/fast/customDictionary.xml
07 Dec 2019 20:46:52  INFO DictionaryDescriptorParser - Parsing dictionary specifications: 
07 Dec 2019 20:46:52 ERROR CtakesRestController - Error loading pipers
07 Dec 2019 20:46:52  WARN XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ctakesRestController': Invocation of init method failed; nested exception is javax.servlet.ServletException: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.concurrent.ThreadSafeFastLookup" failed.  (Descriptor: <unknown>)
07 Dec 2019 20:46:52 ERROR DispatcherServlet - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ctakesRestController': Invocation of init method failed; nested exception is javax.servlet.ServletException: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.concurrent.ThreadSafeFastLookup" failed.  (Descriptor: <unknown>)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:985)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4885)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5199)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.concurrent.ThreadSafeFastLookup" failed.  (Descriptor: <unknown>)
	at org.apache.ctakes.rest.service.CtakesRestController$PipelineRunner.<init>(CtakesRestController.java:93)
	at org.apache.ctakes.rest.service.CtakesRestController$PipelineRunner.<init>(CtakesRestController.java:80)
	at org.apache.ctakes.rest.service.CtakesRestController.init(CtakesRestController.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	... 34 more
Caused by: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.concurrent.ThreadSafeFastLookup" failed.  (Descriptor: <unknown>)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:252)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:156)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:387)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:254)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:431)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:375)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:185)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:354)
	at org.apache.ctakes.rest.service.CtakesRestController$PipelineRunner.<init>(CtakesRestController.java:89)
	... 43 more
Caused by: org.apache.uima.resource.ResourceInitializationException: EXCEPTION MESSAGE LOCALIZATION FAILED: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key Could not parse 
	at org.apache.ctakes.dictionary.lookup2.ae.AbstractJCasTermAnnotator.initialize(AbstractJCasTermAnnotator.java:140)
	at org.apache.ctakes.core.concurrent.ThreadSafeWrapper.initialize(ThreadSafeWrapper.java:52)
	at org.apache.ctakes.dictionary.lookup2.concurrent.ThreadSafeFastLookup.initialize(ThreadSafeFastLookup.java:38)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:250)
	... 57 more
Caused by: org.apache.uima.analysis_engine.annotator.AnnotatorContextException: EXCEPTION MESSAGE LOCALIZATION FAILED: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key Could not parse 
	at org.apache.ctakes.dictionary.lookup2.dictionary.DictionaryDescriptorParser.parseDescriptor(DictionaryDescriptorParser.java:123)
	at org.apache.ctakes.dictionary.lookup2.ae.AbstractJCasTermAnnotator.initialize(AbstractJCasTermAnnotator.java:138)
	... 60 more
Caused by: org.jdom.input.JDOMParseException: Error on line -1: Premature end of file.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:533)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:865)
	at org.apache.ctakes.dictionary.lookup2.dictionary.DictionaryDescriptorParser.parseDescriptor(DictionaryDescriptorParser.java:121)
	... 61 more
Caused by: org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:518)
	... 63 more
07-Dec-2019 20:46:52.275 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ctakes-web-rest.war] has finished in [24,640] ms
07-Dec-2019 20:46:52.282 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
07-Dec-2019 20:46:52.399 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [117] ms
07-Dec-2019 20:46:52.400 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
07-Dec-2019 20:46:52.461 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [60] ms
07-Dec-2019 20:46:52.469 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
07-Dec-2019 20:46:52.514 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [45] ms
07-Dec-2019 20:46:52.517 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
07-Dec-2019 20:46:52.916 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [398] ms
07-Dec-2019 20:46:52.918 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
07-Dec-2019 20:46:52.948 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [30] ms
```

**Comment by MatthewVita** [comment]
This is telling: `Dec 2019 20:46:52 ERROR CtakesRestController - Error loading pipers in the log`

Can you make sure that the piper resources weren't moved around/edited in any way? In case you didn't know (you probably do!), the pipers (in Java) are called out here: `https://github.com/GoTeamEpsilon/ctakes-rest-service/blob/master/ctakes-web-rest/src/main/java/org/apache/ctakes/rest/service/CtakesRestController.java#L48`

.....and the piper files are called out here: `https://github.com/GoTeamEpsilon/ctakes-rest-service/tree/master/ctakes-web-rest/src/main/resources/pipers`

_(Just leaving this note - no action needed right now):_
What do you think of running this Docker image on an Ubuntu base? I know that is a lot more work because of manual Java/Tomcat-related installs, but it may be a bit smoother in the end because it's the norm with the project. It 100% makes sense to work with what we have now, but it may be a good call if we run into issues. There may even be Ubuntu/Java/Tomcat images out there. Just putting this out there!

**Comment by dermatologist** [comment]
I dockerized this but is now stuck on #65. Would you like a PR? 
https://github.com/E-Health/ctakes-rest-service (feature/docker-build). It may not work on the first 'docker-compose up' as the database setup may take time.

**Comment by MatthewVita** [comment]
@dermatologist I'm happy to hear the dockerized solution is in place. Would be great to merge that.

As for issue 65, I am basically at the point where I don't have the resources to work on this project and there is a ctakes rest service based off of this one that is in the official SVN repository. It has better results, however, it uses an n mem/file based DB instead of something like MySQl/Postgres/etc.

That may be something to consider. I honestly cannot figure out 65...

**Comment by dermatologist** [comment]
@MatthewVita Done. Thanks! Will check the official SVN repo.
